### ISSUE TITLE
Fix "similar-code" issue in src/server/auth.ts

### ISSUE THREAD

**Issue by bencooper222** [VandyHacks/vaken#156] opened 2019-05-23 01:19 UTC
Similar blocks of code found in 2 locations. Consider refactoring.

https://codeclimate.com/github/VandyHacks/vaken/src/server/auth.ts#issue_5ce5f38e57953b00010000c9

**Comment by cktang88** [comment] 2019-05-23 01:22
Duplicate of #14 ?

**Closed by cktang88** 2019-05-23 01:22 UTC
Labels: Priority: High, codeclimate
